# Site settings
title: Aaron Nielsen
email: aaron.nielsen@colostate.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a statistician and teaching professor in the Department of Statistics at Colorado State University.1
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaron-nielsen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""