# Site settings
title: Aaron Nielsen
email: aaron-nielsen@colostate.edu
description: blah blah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaron-nielsen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""